### ISSUE TITLE
windows平台使用抛出 “方法没有实现”异常

### ISSUE THREAD

**Issue by CeSun** [BeyondDimension/NotifyIcon#1]
```CSharp
        public static void Main(string[] args)
        {
            NotifyIcon notifyIcon = NotifyIcon.Create();
            notifyIcon.Visible = true;
            BuildAvaloniaApp()
                .StartWithClassicDesktopLifetime(args);
        }
```

异常:
```
Unhandled exception. System.NotImplementedException: The method or operation is not implemented.
   at System.Windows.NotifyIcon.GetImplType()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at System.Windows.NotifyIcon.get_Type()
   at System.Windows.NotifyIcon.Create()
   at Todo.Program.Main(String[] args) in D:\Source\Todo\Todo\Program.cs:line 16
```

依赖:
![image](https://user-images.githubusercontent.com/54771283/133878876-ed1cb4f4-ffa9-4e64-9bb7-d362e3b068ca.png)

**Comment by CeSun** [comment]
平台实现的包也需要引入，此贴终结。

**Comment by AigioL** [comment]
平台实现的包不应该引用，这应该是 1.0.3 版本的一个 bug，目前 1.0.4 版本中已修复
目前 Avalonia 最新的库中已支持 ```Avalonia.Controls.TrayIcon```
https://github.com/AvaloniaUI/Avalonia/pull/6560
